// お題バンク。ネット不要でセッションを開始できるよう、すべて埋め込み。
// cat: work=仕事の英語 / daily=日常会話 / opinion=意見を言う練習
// en=読み上げ＆表示するお題、ja=答えたあとに出す日本語ヒント（先に見ないのが基本）

const PROMPTS = [
  // ── 仕事の英語（構造設計・現場・打合せ）────────────────────────
  { id: 'w01', cat: 'work', en: 'How was your meeting today?', ja: '今日の打合せどうだった？' },
  { id: 'w02', cat: 'work', en: 'What are you working on this week?', ja: '今週は何をやってる？' },
  { id: 'w03', cat: 'work', en: 'Can you explain what a structural engineer does?', ja: '構造設計者の仕事を説明して' },
  { id: 'w04', cat: 'work', en: 'The client wants to change the layout. What do you tell them?', ja: '施主が間取り変更を希望。どう答える？' },
  { id: 'w05', cat: 'work', en: 'Why is the schedule delayed? Explain it to your boss.', ja: '遅延の理由を上司に説明' },
  { id: 'w06', cat: 'work', en: 'Describe the building you are designing right now.', ja: '今設計中の建物を説明' },
  { id: 'w07', cat: 'work', en: 'A contractor found a problem on site. How do you respond?', ja: '現場で問題発覚。どう返す？' },
  { id: 'w08', cat: 'work', en: 'Explain the difference between design in Japan and in Vietnam.', ja: '日本とベトナムの設計の違い' },
  { id: 'w09', cat: 'work', en: 'Someone asks for a deadline you cannot meet. What do you say?', ja: '無理な納期を求められた' },
  { id: 'w10', cat: 'work', en: 'Introduce yourself and your job in 20 seconds.', ja: '自己紹介と仕事を20秒で' },
  { id: 'w11', cat: 'work', en: 'Explain why the foundation design takes so much time.', ja: '基礎設計に時間がかかる理由' },
  { id: 'w12', cat: 'work', en: 'You disagree with the architect. How do you say it politely?', ja: '意匠設計者に丁寧に反対する' },
  { id: 'w13', cat: 'work', en: 'Summarize what happened at work yesterday.', ja: '昨日の仕事を要約' },
  { id: 'w14', cat: 'work', en: 'Ask a colleague to check your drawings, and say why.', ja: '図面チェックを依頼する' },
  { id: 'w15', cat: 'work', en: 'How do you decide the size of a column?', ja: '柱断面をどう決める？' },
  { id: 'w16', cat: 'work', en: 'Explain earthquake design to someone with no background.', ja: '素人に耐震設計を説明' },
  { id: 'w17', cat: 'work', en: 'Your calculation was wrong. How do you report it?', ja: '自分の計算ミスを報告する' },
  { id: 'w18', cat: 'work', en: 'What software do you use, and what do you like about it?', ja: '使うソフトと良いところ' },
  { id: 'w19', cat: 'work', en: 'Describe a project you are proud of.', ja: '誇れるプロジェクト' },
  { id: 'w20', cat: 'work', en: 'The budget was cut. What do you propose?', ja: '予算削減。何を提案する？' },
  { id: 'w21', cat: 'work', en: 'Explain your role to a new team member.', ja: '新人に自分の役割を説明' },
  { id: 'w22', cat: 'work', en: 'What is the hardest part of your job?', ja: '仕事で一番大変なこと' },
  { id: 'w23', cat: 'work', en: 'Ask for more information about a request you did not understand.', ja: '分からない依頼を聞き返す' },
  { id: 'w24', cat: 'work', en: 'Give a two-sentence progress update on your current project.', ja: '進捗を2文で報告' },
  { id: 'w25', cat: 'work', en: 'A meeting is running long. How do you wrap it up?', ja: '長引く会議をまとめる' },
  { id: 'w26', cat: 'work', en: 'Explain what you checked before approving a drawing.', ja: '承認前に何を確認したか' },
  { id: 'w27', cat: 'work', en: 'Describe your typical working day.', ja: '典型的な一日' },
  { id: 'w28', cat: 'work', en: 'Someone blames your team unfairly. How do you reply?', ja: '不当に責められた時の返し' },
  { id: 'w29', cat: 'work', en: 'Explain why safety factors exist.', ja: '安全率がある理由' },
  { id: 'w30', cat: 'work', en: 'What would you change about how your team works?', ja: 'チームの改善したい点' },

  // ── 日常会話 ───────────────────────────────────────────────
  { id: 'd01', cat: 'daily', en: 'What did you do last weekend?', ja: '先週末は何をした？' },
  { id: 'd02', cat: 'daily', en: 'Tell me about your family.', ja: '家族について' },
  { id: 'd03', cat: 'daily', en: 'What is the best meal you have had recently?', ja: '最近食べた一番おいしいもの' },
  { id: 'd04', cat: 'daily', en: 'How do you usually spend your evenings?', ja: '夜はどう過ごす？' },
  { id: 'd05', cat: 'daily', en: 'Describe the city you live in.', ja: '住んでいる街を説明' },
  { id: 'd06', cat: 'daily', en: 'What is the weather like today, and how does it affect you?', ja: '今日の天気とその影響' },
  { id: 'd07', cat: 'daily', en: 'Tell me about a trip you want to take.', ja: '行きたい旅行' },
  { id: 'd08', cat: 'daily', en: 'What do you do to relax?', ja: 'リラックス方法' },
  { id: 'd09', cat: 'daily', en: 'Describe your morning routine.', ja: '朝のルーティン' },
  { id: 'd10', cat: 'daily', en: 'What kind of movies do you like, and why?', ja: '好きな映画とその理由' },
  { id: 'd11', cat: 'daily', en: 'Tell me about something that made you laugh recently.', ja: '最近笑ったこと' },
  { id: 'd12', cat: 'daily', en: 'How did you learn English so far?', ja: 'これまでの英語学習' },
  { id: 'd13', cat: 'daily', en: 'What is your favorite place in your house?', ja: '家で一番好きな場所' },
  { id: 'd14', cat: 'daily', en: 'Describe a person you admire.', ja: '尊敬する人' },
  { id: 'd15', cat: 'daily', en: 'What did you eat for breakfast, and is that usual?', ja: '朝食といつも通りか' },
  { id: 'd16', cat: 'daily', en: 'Tell me about a hobby you would like to start.', ja: '始めたい趣味' },
  { id: 'd17', cat: 'daily', en: 'What is something you bought recently that you like?', ja: '最近買って良かったもの' },
  { id: 'd18', cat: 'daily', en: 'Describe your commute.', ja: '通勤について' },
  { id: 'd19', cat: 'daily', en: 'What do you usually do on holidays?', ja: '休日の過ごし方' },
  { id: 'd20', cat: 'daily', en: 'Tell me about your childhood town.', ja: '子どもの頃の街' },
  { id: 'd21', cat: 'daily', en: 'What is a small thing that makes your day better?', ja: '一日が良くなる小さなこと' },
  { id: 'd22', cat: 'daily', en: 'Describe a difficult situation you handled well.', ja: 'うまく乗り切った場面' },
  { id: 'd23', cat: 'daily', en: 'What music do you listen to while working?', ja: '作業中に聴く音楽' },
  { id: 'd24', cat: 'daily', en: 'Tell me about a book or video that changed your mind.', ja: '考えを変えた本や動画' },
  { id: 'd25', cat: 'daily', en: 'How do you keep in touch with old friends?', ja: '旧友との連絡' },
  { id: 'd26', cat: 'daily', en: 'What is your plan for the rest of the week?', ja: '今週の残りの予定' },
  { id: 'd27', cat: 'daily', en: 'Describe your ideal weekend.', ja: '理想の週末' },
  { id: 'd28', cat: 'daily', en: 'What is something you are looking forward to?', ja: '楽しみにしていること' },
  { id: 'd29', cat: 'daily', en: 'Tell me about a place you go often.', ja: 'よく行く場所' },
  { id: 'd30', cat: 'daily', en: 'What did you struggle with today?', ja: '今日苦労したこと' },

  // ── 意見を言う練習 ─────────────────────────────────────────
  { id: 'o01', cat: 'opinion', en: 'Is working from home better than working in an office? Why?', ja: '在宅と出社、どちらが良い？' },
  { id: 'o02', cat: 'opinion', en: 'Should AI be used in engineering design? What do you think?', ja: 'AIを設計に使うべきか' },
  { id: 'o03', cat: 'opinion', en: 'What is more important: speed or quality?', ja: 'スピードと品質、どちらが大事？' },
  { id: 'o04', cat: 'opinion', en: 'Do you think everyone should learn a second language?', ja: '第二言語は全員必要か' },
  { id: 'o05', cat: 'opinion', en: 'Are long meetings ever useful? Explain your view.', ja: '長い会議は有用か' },
  { id: 'o06', cat: 'opinion', en: 'Is it better to specialize or to be a generalist?', ja: '専門特化か何でも屋か' },
  { id: 'o07', cat: 'opinion', en: 'Should companies pay for employees to study? Why?', ja: '会社が学習費を出すべきか' },
  { id: 'o08', cat: 'opinion', en: 'What do you think about living abroad long term?', ja: '長期の海外生活をどう思う？' },
  { id: 'o09', cat: 'opinion', en: 'Is it worth buying a house, or is renting better?', ja: '持ち家か賃貸か' },
  { id: 'o10', cat: 'opinion', en: 'Do you think old buildings should be preserved or replaced?', ja: '古い建物は保存か建替えか' },
  { id: 'o11', cat: 'opinion', en: 'What is the biggest problem in your industry?', ja: '業界の最大の問題' },
  { id: 'o12', cat: 'opinion', en: 'Should engineers learn programming? Why or why not?', ja: '技術者はプログラミングを学ぶべきか' },
  { id: 'o13', cat: 'opinion', en: 'Is it better to change jobs often or stay at one company?', ja: '転職か一社か' },
  { id: 'o14', cat: 'opinion', en: 'What do you think makes a good leader?', ja: '良いリーダーの条件' },
  { id: 'o15', cat: 'opinion', en: 'Should children start English earlier in Japan?', ja: '英語教育の開始年齢' },
  { id: 'o16', cat: 'opinion', en: 'Is remote communication as good as meeting in person?', ja: 'リモートは対面と同等か' },
  { id: 'o17', cat: 'opinion', en: 'What would you change about your industry if you could?', ja: '業界で変えたいこと' },
  { id: 'o18', cat: 'opinion', en: 'Do you think overtime is sometimes necessary?', ja: '残業は必要な時があるか' },
  { id: 'o19', cat: 'opinion', en: 'Is it better to plan carefully or to start and adjust?', ja: '綿密な計画か走りながら修正か' },
  { id: 'o20', cat: 'opinion', en: 'What is your view on electric vehicles?', ja: 'EVについての意見' },
  { id: 'o21', cat: 'opinion', en: 'Should safety rules ever be relaxed to save cost?', ja: 'コストのため安全基準を緩めるか' },
  { id: 'o22', cat: 'opinion', en: 'Is social media good or bad for your life?', ja: 'SNSは良いか悪いか' },
  { id: 'o23', cat: 'opinion', en: 'What advice would you give your 25-year-old self?', ja: '25歳の自分への助言' },
  { id: 'o24', cat: 'opinion', en: 'Do you think Japan should accept more foreign workers?', ja: '外国人労働者の受入れ' },
  { id: 'o25', cat: 'opinion', en: 'Is it important to be liked at work?', ja: '職場で好かれることは重要か' },
  { id: 'o26', cat: 'opinion', en: 'What is the best way to learn a new skill quickly?', ja: '新しい技能の最速習得法' },
  { id: 'o27', cat: 'opinion', en: 'Should design decisions be made by consensus or by one person?', ja: '設計判断は合議か一人か' },
  { id: 'o28', cat: 'opinion', en: 'Do you think stress can be a good thing?', ja: 'ストレスは良いものか' },
  { id: 'o29', cat: 'opinion', en: 'What matters more: experience or new ideas?', ja: '経験か新しい発想か' },
  { id: 'o30', cat: 'opinion', en: 'How should we decide what to automate and what to keep manual?', ja: '自動化と手作業の線引き' },
];

// 4-3-2 リテリング用のトピック（同じ話を 60秒→45秒→30秒 で3回話す）
const RETELL_TOPICS = [
  { id: 'r01', cat: 'work', en: 'Tell the story of a project that did not go as planned.', ja: '計画通りに行かなかった案件の話' },
  { id: 'r02', cat: 'work', en: 'Explain your current project from start to finish.', ja: '今の案件を最初から最後まで' },
  { id: 'r03', cat: 'work', en: 'Tell the story of the hardest problem you solved at work.', ja: '仕事で解決した一番難しい問題' },
  { id: 'r04', cat: 'daily', en: 'Tell the story of your last trip, from leaving home to coming back.', ja: '直近の旅行を出発から帰宅まで' },
  { id: 'r05', cat: 'daily', en: 'Tell me how you ended up living where you live now.', ja: '今の場所に住むまでの経緯' },
  { id: 'r06', cat: 'daily', en: 'Tell the story of a memorable day with your family.', ja: '家族との忘れられない一日' },
  { id: 'r07', cat: 'daily', en: 'Explain how you got into your career, step by step.', ja: '今の仕事に就くまでの流れ' },
  { id: 'r08', cat: 'opinion', en: 'Explain your opinion on how buildings should be designed in 20 years.', ja: '20年後の建物設計はどうあるべきか' },
  { id: 'r09', cat: 'opinion', en: 'Make the case for how your company should use AI.', ja: '自社がAIをどう使うべきか主張する' },
  { id: 'r10', cat: 'daily', en: 'Describe a movie or drama you watched, including the ending.', ja: '観た映画・ドラマを結末まで' },
];

// 出だしが出てこない時に使う「つなぎ」— セッション開始時に1つ提示する
const OPENERS = [
  { en: 'Well, ...', ja: 'まず時間を稼ぐ一言' },
  { en: 'Let me think for a second.', ja: '考える時間をもらう' },
  { en: 'That is a good question.', ja: '定番の時間稼ぎ' },
  { en: 'The thing is, ...', ja: '要点を切り出す' },
  { en: 'To be honest, ...', ja: '正直な意見を出す' },
  { en: 'It depends on ...', ja: '断定を避けて話し始める' },
  { en: 'I would say ...', ja: '意見をやわらかく出す' },
  { en: 'Actually, ...', ja: '話を切り出す・訂正する' },
  { en: 'What I mean is, ...', ja: '言い直す' },
  { en: 'For example, ...', ja: '具体例で間をつなぐ' },
  { en: 'Off the top of my head, ...', ja: 'とっさに思いつく範囲で' },
  { en: 'How can I put this?', ja: '言い方を探す時' },
];
